#!/bin/bash
# SUMMARY: Output to fd3
# HELP:
# USAGE
#    dk cli-tricks triple-stream
#    dk cli-tricks triple-stream 1> /dev/null
#    dk cli-tricks triple-stream 2> /dev/null
#    dk cli-tricks triple-stream 3> /dev/null
#
# DESCRIPTION
#    This script demonstrates how to detect whether fd3 is open and send output
#    to it. This trick is useful if you want to write a script that can produce
#    debug output on an additional stream outside of stdout and stderr.
echo "Text sent to standard out"
echo "Text sent to standard err" >&2

if ! (printf '' 1>&3) 2>&-; then
  # File descriptor 3 is not open
  # Redirect fd3 to the tty.
  exec 3>/dev/tty
fi

echo "Text sent to fd 3" >&3
